### ISSUE TITLE
docker2aci fails to convert the quay.io/kelseyhightower/kubelet:0.19.0 image

### ISSUE THREAD

**Issue by kelseyhightower** [appc/docker2aci#71] opened 2015-06-18 16:44 UTC
docker2aci does not generate the right set of volumes when converting the quay.io/kelseyhightower/kubelet:0.19.0 Docker image. Seems to have trouble translating volumes defined in an JSON array:

```
docker2aci docker://quay.io/kelseyhightower/kubelet:0.19.0
Downloading c6b09d8961e4: [====================================] 32 B/32 B
Downloading d988518ba01b: [====================================] 7.92 MB/7.92 MB
Downloading 51fa9c9fc1bb: [====================================] 32 B/32 B
Downloading c6d0abb02258: [====================================] 32 B/32 B

Converted volumes:
	name: "volume-rootfs", path: "/rootfs,", readOnly: false
	name: "volume-sys", path: "/sys,", readOnly: false
	name: "volume-var-lib-kubelet", path: "/var/lib/kubelet,", readOnly: false
	name: "volume-var-run", path: "/var/run,", readOnly: false
	name: "volume-etc-kubernetes", path: "/etc/kubernetes,", readOnly: false
	name: "volume-etc-ssl-certs", path: "/etc/ssl/certs", readOnly: false
	name: "volume-lib64", path: "/lib64]", readOnly: false
	name: "volume-nsenter", path: "/nsenter,", readOnly: false
	name: "volume-usr", path: "/usr,", readOnly: false
	name: "volume---var-lib-docker", path: "[/var/lib/docker,", readOnly: false

Generated ACI(s):
kelseyhightower-kubelet-0.19.0.aci
```

The resulting manifest looks like this:

```
{
   "acKind":"ImageManifest",
   "acVersion":"0.5.1",
   "name":"quay.io/kelseyhightower/kubelet",
   "labels":[
      {
         "name":"version",
         "value":"0.19.0"
      },
      {
         "name":"os",
         "value":"linux"
      }
   ],
   "app":{
      "exec":[
         "/kubelet"
      ],
      "user":"0",
      "group":"0",
      "mountPoints":[
         {
            "name":"volume-rootfs",
            "path":"/rootfs,"
         },
         {
            "name":"volume-sys",
            "path":"/sys,"
         },
         {
            "name":"volume-var-lib-kubelet",
            "path":"/var/lib/kubelet,"
         },
         {
            "name":"volume-var-run",
            "path":"/var/run,"
         },
         {
            "name":"volume-etc-kubernetes",
            "path":"/etc/kubernetes,"
         },
         {
            "name":"volume-etc-ssl-certs",
            "path":"/etc/ssl/certs"
         },
         {
            "name":"volume-lib64",
            "path":"/lib64]"
         },
         {
            "name":"volume-nsenter",
            "path":"/nsenter,"
         },
         {
            "name":"volume-usr",
            "path":"/usr,"
         },
         {
            "name":"volume---var-lib-docker",
            "path":"[/var/lib/docker,"
         }
      ]
   },
   "annotations":[
      {
         "name":"authors",
         "value":"Kelsey Hightower \u003ckelsey.hightower@gmail.com\u003e"
      },
      {
         "name":"created",
         "value":"2015-06-18T01:24:39Z"
      }
   ]
}
```

**Comment by kelseyhightower** [comment] 2015-06-18 17:41
After making the following adjustments to the docker file, I get something that works for me. This is still a bug if we want to support volumes defined in a JSON array.

The fix is to not use a JSON array to define volumes in the docker file.

```
VOLUME /var/lib/docker /var/lib/kubelet /var/run /sys /etc/kubernetes /etc/ssl/certs /rootfs /nsenter /usr /lib64
```


The results
```
$ docker2aci docker://quay.io/kelseyhightower/kubelet:0.19.0
Downloading c6b09d8961e4: [====================================] 32 B/32 B
Downloading 57858edd3470: [====================================] 7.92 MB/7.92 MB
Downloading 1a4168fc39d8: [====================================] 32 B/32 B
Downloading 92c62d2e9e70: [====================================] 32 B/32 B

Converted volumes:
	name: "volume-nsenter", path: "/nsenter", readOnly: false
	name: "volume-rootfs", path: "/rootfs", readOnly: false
	name: "volume-usr", path: "/usr", readOnly: false
	name: "volume-var-lib-kubelet", path: "/var/lib/kubelet", readOnly: false
	name: "volume-var-run", path: "/var/run", readOnly: false
	name: "volume-etc-kubernetes", path: "/etc/kubernetes", readOnly: false
	name: "volume-etc-ssl-certs", path: "/etc/ssl/certs", readOnly: false
	name: "volume-lib64", path: "/lib64", readOnly: false
	name: "volume-sys", path: "/sys", readOnly: false
	name: "volume-var-lib-docker", path: "/var/lib/docker", readOnly: false

Generated ACI(s):
kelseyhightower-kubelet-0.19.0.aci
```

**Comment by yifan-gu** [comment] 2015-06-18 18:11
@kelseyhightower Thanks for reporting will take a look :)

**Comment by iaguis** [comment] 2015-06-30 15:38
I'm trying to reproduce this without success.

Dockerfile:

```
FROM scratch

ADD busybox /bin/busybox

VOLUME ["/test", "/test2"]

CMD ["/bin/busybox", "sh"]
```

Then:

```
iaguis@locke-work: ~/temp/rkt/volumes
> docker build .
Sending build context to Docker daemon 934.4 kB
Sending build context to Docker daemon 
Step 0 : FROM scratch
 ---> 
Step 1 : ADD busybox /bin/busybox
 ---> 7e366b67d1b0
Removing intermediate container 571daf6eb9c5
Step 2 : VOLUME /test /test2
 ---> Running in 617a8f290200
 ---> b25c82585106
Removing intermediate container 617a8f290200
Step 3 : CMD /bin/busybox sh
 ---> Running in 828c1bb9b0c3
 ---> 7e860c3a005e
Removing intermediate container 828c1bb9b0c3
Successfully built 7e860c3a005e
iaguis@locke-work: ~/temp/rkt/volumes
> docker tag  7e860c3a005e busybox-test-volumes
iaguis@locke-work: ~/temp/rkt/volumes
> docker save -o test-volumes.docker busybox-test-volumes
iaguis@locke-work: ~/temp/rkt/volumes
> docker2aci test-volumes.docker 
Extracting 7e366b67d1b0
Extracting b25c82585106
Extracting 7e860c3a005e

Converted volumes:
        name: "volume-test", path: "/test", readOnly: false
        name: "volume-test2", path: "/test2", readOnly: false

Generated ACI(s):
busybox-test-volumes-latest.aci
iaguis@locke-work: ~/temp/rkt/volumes
> actool cat-manifest --pretty-print busybox-test-volumes-latest.aci
{
    "acKind": "ImageManifest",
    "acVersion": "0.5.1",
    "name": "busybox-test-volumes",
    "labels": [
        {
            "name": "version",
            "value": "latest"
        },
        {
            "name": "os",
            "value": "linux"
        }
    ],
    "app": {
        "exec": [
            "/bin/busybox",
            "sh"
        ],
        "user": "0",
        "group": "0",
        "mountPoints": [
            {
                "name": "volume-test",
                "path": "/test"
            },
            {
                "name": "volume-test2",
                "path": "/test2"
            }
        ]
    },
    "annotations": [
        {
            "name": "created",
            "value": "2015-06-30T15:33:00Z"
        }
    ]
}
```

**Comment by jonboulle** [comment] 2015-06-30 18:12
@iaguis does it reproduce consistently with kelsey's image?

**Comment by iaguis** [comment] 2015-06-30 18:16
He [adjusted his Dockerfile](https://github.com/appc/docker2aci/issues/71#issuecomment-113232092) so I can't reproduce it either.

**Comment by jonboulle** [comment] 2015-06-30 18:17
oh right, docker images aren't immutable ;-)

**Comment by jonboulle** [comment] 2015-09-15 20:33
Closing as we couldn't reproduce.

**Closed by jonboulle** 2015-09-15 20:33 UTC
