### ISSUE TITLE
Error: conversion error: error generating ACI: archive/tar: cannot encode header

### ISSUE THREAD

**Issue by zhsj** [appc/docker2aci#259] opened 2018-02-26 17:30 UTC
While running `docker2aci -debug docker://docker.elastic.co/kibana/kibana:6.1.3` it shows:

```
Error: conversion error: error generating ACI: archive/tar: cannot encode header: Format specifies USTAR; and USTAR cannot encode Linkname="rootfs/var/lib/yum/yumdb/a/6f8ba1fc41ecc5f60aac5b4b7aa28d2566c55481-audit-libs-2.7.6-3.el7-x86_64/from_repo"
```

The error comes from

https://github.com/appc/docker2aci/blob/365911f6aa7f0a9a324a27bb6da0f7755df43041/lib/internal/internal.go#L632

`t.Header.Format` is `USTAR` here. The call to `tar.WriteHeader` triggers the error.

`t.Header` is parsed from 

https://github.com/appc/docker2aci/blob/365911f6aa7f0a9a324a27bb6da0f7755df43041/lib/internal/tarball/walk.go#L30

which is also from Go std lib `archive/tar`.

So, I think the fault is not `docker2aci`. But should `dokcer2aci` do some tricks to work around this?

One approach is to unset the `t.Header.Format`, at least it works for me currently.

```
diff --git a/lib/internal/internal.go b/lib/internal/internal.go
index 1f811fc..d694c39 100644
--- a/lib/internal/internal.go
+++ b/lib/internal/internal.go
@@ -609,6 +609,7 @@ func writeACI(layer io.ReadSeeker, manifest schema.ImageManifest, curPwl []strin
        fileMap := make(map[string]struct{})
        var whiteouts []string
        convWalker := func(t *tarball.TarFile) error {
+               t.Header.Format = tar.FormatUnknown
                name := t.Name()
                if name == "./" {
                        return nil
```

Any suggestions?

**Comment by zhsj** [comment] 2018-02-26 19:16
The previous comment is false, the error is still in appc/docker2aci

https://github.com/appc/docker2aci/blob/365911f6aa7f0a9a324a27bb6da0f7755df43041/lib/internal/internal.go#L629

Here, the `len(Linkname) > 100`, making the `t.Header.Format` which is USTAR invalid.

**Comment by lucab** [comment] 2018-04-12 09:09
How did you build this `docker2aci` binary? I'm starting to suspect that this is a regression in Go 1.10. If I try with the binary attached to the github release or with one locally build with go-1.9, I can't seem to reproduce this.

**Comment by zhsj** [comment] 2018-04-12 09:18
@lucab tried myself, and I can confirm the binary on github release is find. And the one built by Go 1.10 failed.

The build method is nothing special, just `go build`.

**Comment by lucab** [comment] 2018-04-12 09:55
Thanks for confirming, that's also the behavior I see with a local go-1.10 build. I reported the regression to https://github.com/golang/go/issues/24821, and I'd be happier if this turns out to be directly fixed in `archive/tar`.

**Closed** 2018-04-13 14:58 UTC
