### ISSUE TITLE
Missing os label in the image manifest

### ISSUE THREAD

**Issue by yifan-gu** [appc/docker2aci#192] opened 2016-08-04 23:30 UTC
Was trying to run some etcd image today:

```
$ sudo rkt run --insecure-options=image docker://quay.io/coreos/etcd:latest
image: using image from file /home/yifan/gopher/src/github.com/coreos/rkt/build-rkt-1.11.0+git/target/bin/stage1-coreos.aci
image: using image from local store for url docker://quay.io/coreos/etcd:latest
run: error setting up stage0: missing os label in the image manifest
```

**Comment by yifan-gu** [comment] 2016-08-04 23:30
cc @xiang90

**Comment by sgotti** [comment] 2016-08-05 07:29
This should have been fixed by #189 or #190. I cannot reproduce it with rkt 1.12.

```
sudo rkt prepare --insecure-options=image docker://quay.io/coreos/etcd:latest                                                                                          
image: using image from file /home/motaboy/golang/src/github.com/coreos/rkt/build-rkt-1.12.0+git/target/bin/stage1-coreos.aci
image: remote fetching from URL "docker://quay.io/coreos/etcd:latest"
Downloading sha256:3d7ea97af22 [=============================]     130 B / 130 B
Downloading sha256:a3ed95caeb0 [=============================]       32 B / 32 B
Downloading sha256:a3ed95caeb0 [=============================]       32 B / 32 B
Downloading sha256:699b80a62e3 [=============================] 5.27 MB / 5.27 MB
Downloading sha256:a8c34e20dd1 [=============================]     110 B / 110 B
Downloading sha256:e110a4a1794 [=============================] 2.31 MB / 2.31 MB
Downloading sha256:fb7f87d1994 [=============================]   4.8 MB / 4.8 MB
2e8a680d-27d4-4f5e-ad45-fd9723461b60

**Comment by iaguis** [comment] 2016-08-05 10:32
Me neither, closing. Reopen if you still have problems.

**Closed by iaguis** 2016-08-05 10:32 UTC

**Comment by yifan-gu** [comment] 2016-08-05 20:06
Thanks guys.
